spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama3-8b-8192




spring.ai.ollama.embedding.options.model=nomic-embed-text
